src/Entity/ContentInvoice.php
<?php

namespace App\Entity;

use App\Repository\ContentInvoiceRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContentInvoiceRepository::class)]
class ContentInvoice
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Invoice::class, inversedBy: 'contentInvoices')]
    #[ORM\JoinColumn(nullable: false)]
    private $invoice;

    #[ORM\Column(type: 'string', length: 255)]
    private $productName;

    #[ORM\Column(type: 'integer')]
    private $priceProduct;

    #[ORM\Column(type: 'string', length: 255)]
    private $imageProduct;

    #[ORM\Column(type: 'integer')]
    private $quantity;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInvoice(): ?Invoice
    {
        return $this->invoice;
    }

    public function setInvoice(?Invoice $invoice): self
    {
        $this->invoice = $invoice;

        return $this;
    }

    public function getProductName(): ?string
    {
        return $this->productName;
    }

    public function setProductName(string $productName): self
    {
        $this->productName = $productName;

        return $this;
    }

    public function getPriceProduct(): ?int
    {
        return $this->priceProduct;
    }

    public function setPriceProduct(int $priceProduct): self
    {
        $this->priceProduct = $priceProduct;

        return $this;
    }

    public function getImageProduct(): ?string
    {
        return $this->imageProduct;
    }

    public function setImageProduct(string $imageProduct): self
    {
        $this->imageProduct = $imageProduct;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getTotal()
    {
        return $this->getPriceProduct() * $this->getQuantity();
    }
}

templates/customer/home.html.twig
{% extends "base.html.twig" %}

{% block body %}

  <section class="bg">
    <div class="container py-5">
    <div class="row">

          <a id="haut"></a>
           <a class="btn btn-outline-dark" href="mailto:amelie.factory@outlook.fr">Pour toute commande, c'est ici</a>
      
          <div class="col-12">
            <h3 class="text-center">Les nouveautés</h3>
          </div>  
          <hr>
          
                 {% for product in products %}

            <div class="col-sm-12 col-lg-4 mt-3">
              
             <div class="card bg-dark text-white">
                    <img src="{{ product.imagePath }}" class="card-img" alt="image_category">
                  <div class="card-img-overlay">
                
                    </div>
                </div>
                   <h5 class="card-title">{{ product.name }}</h5>
                        <p>{{ product.price | priceEuro }}</p>
                        <a href="{{ path('boutique_product_detail',{'id': product.id} ) }}" class="btn btn-outline-dark btn-lg w-100">Consulter</a>
            </div>
              
            
        {% endfor %}

      </div>
    </div>
  </section>

  <section>
  <div class="container py-5">
      <div class="row">
        <div class="col-12">
          <h3 class="text-center">Les catégories</h3>
        </div>  
        <hr>

  {% for category in categories %}
     
              <div class="col-sm-12 col-lg-4 mt-3">

                 <div class="card bg-dark text-white">
                      <img src="{{ category.imagePath }}" class="card-img" alt="image_category">
                      <div class="card-img-overlay">
                    
                      </div>
                  </div>
                <h5 class="card-title">{{ category.name }}</h5>
                          <a href="{{ path('boutique_product_show_by_category',{'id': category.id}) }}" class="btn btn-outline-dark w-100">Consulter</a>
              </div>
              
          {% endfor %}
    </div>
     </div>
  </section>

  
   


{% endblock %}

templates/customer/panier.html.twig
{% extends "base.html.twig" %}

{% block body %}

    <section>
        <div class="container py-5">
            <div class="row">
                <div class="col-12 mb-3">
                    <h3 class="text-center">Les produits du panier</h3>
                </div>
                {% include "_messages_flash.html.twig" %}
                {% if detailProducts | length > 0 %}
               
                <div class="col-12 mb-3">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Produit</th>
                                <th scope="col">Prix Unitaire</th>
                                <th scope="col">Quantité</th>
                                <th scope="col">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in detailProducts %}
                                <tr>
                                    <th>
                                        <div class="d-flex align-items-center">
                                            <img src="{{ item.product.imagePath }}" alt="" style="height:80px;object-fit:contain;">
                                            <div class="d-flex flex-column align-items-center">
                                                <p>{{ item.product.name }}</p>
                                                <a class="btn btn-link text-danger" href="{{ path('cart_remove_product',{'id': item.product.id }) }}">Supprimer</a>
                                            </div>
                                           
                                        </div>
                                    </th>
                                    <td>{{ item.product.price | priceEuro }}</td>
                                    <td>
                                        <a class="btn btn-dark" href="{{ path('cart_decrement_product',{'id' : item.product.id }) }}"><i class="fas fa-minus-circle"></i></a>
                                        <button class="btn btn-light"> {{ item.qty }}</button>
                                        <a class="btn btn-dark" href="{{ path('cart_add',{'id' : item.product.id }) }}?routeToRedirect=panier"><i class="fas fa-plus-circle"></i></a>
                                    </td>
                                    <td>{{ item.total | priceEuro }}</td>
                                </tr>
                            {% endfor %}
                            <tr>
                                <th colspan="2">
                                </th>
                                <th>
                                    <p><strong>Total</strong></p>
                                </th>
                                <th>
                                    <p><strong>{{ totalPrixPanier | priceEuro}}</strong></p>
                                </th>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-12 d-flex justify-content-end">
                    <a href="{{ path('boutique_commande_recap') }}" class="btn btn-success">Valider le panier</a>
                </div>
                {% else %}

                <p>Votre panier est vide</p>

                <div class="col-12 d-flex">
                    <a href="{{ path('home') }}" class="btn btn-secondary btn-lg btn-block">Voulez-vous retourner sur la page d'acceuil ?</a>
                </div>

                {% endif %} 
            </div>
        </div>
    </section>

{% endblock %}